name: secure_vault
description: A private, secure, and offline mobile document wallet.
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Epic 1: Auth & Encryption ---
  flutter_secure_storage: ^9.2.2  # For storing the Master Encryption Key (MEK) in Keystore
  local_auth: ^2.2.0           # For biometric (fingerprint/face) authentication
  crypto: ^3.0.3                 # For hashing the user's PIN
  shared_preferences: ^2.2.3   # For storing the non-sensitive PIN hash

  # --- Epic 2 & 3: Database & File Management ---
  isar: ^3.1.0+1                 # High-performance NoSQL database
  isar_flutter_libs: ^3.1.0+1    # Bindings for Isar
  path_provider: ^2.1.3        # To find the app's private storage directory
  encrypt: ^5.0.3                # For AES encryption/decryption of files
  file_picker: ^8.0.6            # To pick files (images, PDFs) to add to the vault
  flutter_pdfview: ^1.3.2        # For rendering PDF documents inside the app
  photo_view: ^0.15.0            # For zoomable image viewing

  # --- Epic 4: Backup & Restore ---
  archive: ^3.5.1                # For creating/reading ZIP archives for backups

  # --- Utilities ---
  provider: ^6.1.2               # For simple state management
  google_fonts: ^6.2.1           # For using the Inter font (or others)
  intl: ^0.19.0                  # For date formatting (e.g., expiry dates)


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # --- Database Code Generation ---
  isar_generator: ^3.1.0+1       # Generates code for the Isar database models
  build_runner: ^2.4.11          # Runs code generators

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets: section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
