import 'package:isar/isar.dart';

part 'document_model.g.dart'; // This file will be auto-generated by Isar

// --- Enums ---
// Defines the category of the document for filtering.
@Enumerated(EnumType.name)
enum DocumentCategory {
  Passport,
  Aadhaar,
  License,
  PAN,
  Insurance,
  Vehicle,
  Health,
  Other,
}

// Defines the type of attachment for showing the correct icon/viewer.
@Enumerated(EnumType.name)
enum AttachmentType {
  Image,
  PDF,
  Document, // .doc, .txt
  Spreadsheet, // .xls, .csv
  Other,
}

// --- Main Collection ---
@Collection()
class Document {
  Id id = Isar.autoIncrement; // Auto-incrementing primary key

  @Index() // Index for fast search by title
  late String title;

  @Index(type: IndexType.value) // Index for fast search by number
  String? documentNumber;

  @Index() // Index for fast filtering by category
  @Enumerated(EnumType.name)
  late DocumentCategory category;

  DateTime? expiryDate;

  String? notes;

  late DateTime createdAt; // To sort by "recently added"

  // This stores the list of file pointers.
  // The actual files are encrypted on disk.
  late List<Attachment> attachments;

  // Constructor
  Document({
    required this.title,
    required this.category,
    required this.createdAt,
    this.documentNumber,
    this.expiryDate,
    this.notes,
    this.attachments = const [],
  });
}

// --- Embedded Object ---
// This object is "embedded" inside the Document. It does not have its own
// collection in the database.
@Embedded()
class Attachment {
  String originalFileName = ''; // e.g., "passport_front.jpg"
  String encryptedFilePath = ''; // e.g., "8a7b-c9d2-e5f6.dat"

  @Enumerated(EnumType.name)
  AttachmentType type = AttachmentType.Other;

  // Constructor
  Attachment({
    this.originalFileName = '',
    this.encryptedFilePath = '',
    this.type = AttachmentType.Other,
  });
}
